server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名构建动态路由
      routes:
        - id: payment_routh             #路由的ID，没有固定规则，但是要求唯一，建议配合服务名
#          uri: http://localhost:8001    #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**      #断言，路径相匹配的进行路由

        - id: payment_routh2            #路由的ID，没有固定规则，但是要求唯一，建议配合服务名
#          uri: http://localhost:8001    #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**       #断言，路径相匹配的进行路由
            - After=2021-10-14T09:29:14.440+08:00[Asia/Shanghai]  #指定该路由在哪个时间之后生效，在该时间之前该路由无法访问
#            - Cookie=username,zzyy  #该cookie断言需要访问该路由的源头带入cookie才能访问，且该cookie需要和这个配置的正则表达式相匹配才允许访问（共两个参数，键+正则表达式的值）
#            - Header=X-Request-Id，\d+ #q请求头要有X-Request-Id属性且值为整数的正则表达式(未验证成功，找不到原因）

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka/