server:
  port: 80

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

#设置feign客户端超时时间（OpenFeign默认支持Ribbon）
ribbon:
#  指的是建立连接所用的时间，适用8于网络状况良好的情况下，两端连接所用的时间
  ReadTimeout: 5000
#  指的是建立连接后从服务器读取可用资源所用的时间
  ConnectTimeout: 5000
